#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketBillingService.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProductsDB")]
	public partial class ProductsDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProducts_Detail(Products_Detail instance);
    partial void UpdateProducts_Detail(Products_Detail instance);
    partial void DeleteProducts_Detail(Products_Detail instance);
    #endregion
		
		public ProductsDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProductsDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Products_Detail> Products_Details
		{
			get
			{
				return this.GetTable<Products_Detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products_Details")]
	public partial class Products_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SL_NO;
		
		private string _SKU_PRODUCT_ID;
		
		private string _PRODUCT_DESC;
		
		private System.Nullable<decimal> _PRODUCT_UNIT_PRICE;
		
		private System.Nullable<int> _PRODUCT_COUNT_OFFER;
		
		private System.Nullable<decimal> _PRODUCT_OFFER_PRICE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSL_NOChanging(int value);
    partial void OnSL_NOChanged();
    partial void OnSKU_PRODUCT_IDChanging(string value);
    partial void OnSKU_PRODUCT_IDChanged();
    partial void OnPRODUCT_DESCChanging(string value);
    partial void OnPRODUCT_DESCChanged();
    partial void OnPRODUCT_UNIT_PRICEChanging(System.Nullable<decimal> value);
    partial void OnPRODUCT_UNIT_PRICEChanged();
    partial void OnPRODUCT_COUNT_OFFERChanging(System.Nullable<int> value);
    partial void OnPRODUCT_COUNT_OFFERChanged();
    partial void OnPRODUCT_OFFER_PRICEChanging(System.Nullable<decimal> value);
    partial void OnPRODUCT_OFFER_PRICEChanged();
    #endregion
		
		public Products_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_NO", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int SL_NO
		{
			get
			{
				return this._SL_NO;
			}
			set
			{
				if ((this._SL_NO != value))
				{
					this.OnSL_NOChanging(value);
					this.SendPropertyChanging();
					this._SL_NO = value;
					this.SendPropertyChanged("SL_NO");
					this.OnSL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU_PRODUCT_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SKU_PRODUCT_ID
		{
			get
			{
				return this._SKU_PRODUCT_ID;
			}
			set
			{
				if ((this._SKU_PRODUCT_ID != value))
				{
					this.OnSKU_PRODUCT_IDChanging(value);
					this.SendPropertyChanging();
					this._SKU_PRODUCT_ID = value;
					this.SendPropertyChanged("SKU_PRODUCT_ID");
					this.OnSKU_PRODUCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_DESC", DbType="VarChar(20)")]
		public string PRODUCT_DESC
		{
			get
			{
				return this._PRODUCT_DESC;
			}
			set
			{
				if ((this._PRODUCT_DESC != value))
				{
					this.OnPRODUCT_DESCChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_DESC = value;
					this.SendPropertyChanged("PRODUCT_DESC");
					this.OnPRODUCT_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_UNIT_PRICE", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRODUCT_UNIT_PRICE
		{
			get
			{
				return this._PRODUCT_UNIT_PRICE;
			}
			set
			{
				if ((this._PRODUCT_UNIT_PRICE != value))
				{
					this.OnPRODUCT_UNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_UNIT_PRICE = value;
					this.SendPropertyChanged("PRODUCT_UNIT_PRICE");
					this.OnPRODUCT_UNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_COUNT_OFFER", DbType="Int")]
		public System.Nullable<int> PRODUCT_COUNT_OFFER
		{
			get
			{
				return this._PRODUCT_COUNT_OFFER;
			}
			set
			{
				if ((this._PRODUCT_COUNT_OFFER != value))
				{
					this.OnPRODUCT_COUNT_OFFERChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_COUNT_OFFER = value;
					this.SendPropertyChanged("PRODUCT_COUNT_OFFER");
					this.OnPRODUCT_COUNT_OFFERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_OFFER_PRICE", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRODUCT_OFFER_PRICE
		{
			get
			{
				return this._PRODUCT_OFFER_PRICE;
			}
			set
			{
				if ((this._PRODUCT_OFFER_PRICE != value))
				{
					this.OnPRODUCT_OFFER_PRICEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_OFFER_PRICE = value;
					this.SendPropertyChanged("PRODUCT_OFFER_PRICE");
					this.OnPRODUCT_OFFER_PRICEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
